# Generated by Django 5.1.1 on 2024-10-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("python_drf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.TextField()),
                ("url", models.TextField()),
                ("categories", models.ManyToManyField(to="python_drf.category")),
            ],
        ),
    ]
